### ISSUE TITLE
Undefined Variable 'data_nona' in Function '_pre_process_did'

### ISSUE THREAD

**Issue by flowerpower13** [d2cml-ai/csdid#15]
The function _pre_process_did references a variable named data_nona on lines 55, 56, 75, and 76. However, the variable data_nona is not defined within the scope of the function, which can lead to runtime errors and unexpected behavior when the function is executed.

Steps to Reproduce:

Navigate to the file containing the _pre_process_did function.
Observe lines 5, 56, 75, and 76 where the variable data_nona is referenced.

**Comment by TJhon** [comment]
Thank you, there were indeed variable naming errors within `preprocess_did.py`, they have now been corrected in PR #16.
